### PR TITLE
Draft: Add support for conditional includes

### PR DESCRIPTION
**Pull request by storypku**
+ clang python bindings introduced as external dependency

@martis42 ,
I have implemented conditional includes support for DWYU based on `clang.cindex`, more unit tests and acceptance tests on the way.  I would appreciate it if you could help review this "big" PR in your spare time. 
Known bad practice:
- It's a bad practice to check in pre-built `libclang.so` and `clang.cindex` as an external dependency.
Do you have any suggestions on how to better handle external dependency in such situation?

### CODE REVIEW

**Comment by martis42** [comment]
Unfortunately I don't have much time available for this project at the moment. I don't know when I will have time to look at this huge PR in detail.

Please note, unless https://github.com/martis42/depend_on_what_you_use/issues/11is decided pro "clang based" I would not merge this PR.

Regarding your concrete question.
Typically one looks for an upstream source of pre-compiled binaries for clang and then downloads them via `http_archive` and uses select statements and the platforms concept to choose the correct binary for the current execution platform.
Alternatively one introduces a toolchain and tells the user to provide clang in any way he/she sees befitting while configuring the toolchain.

**Comment by storypku** [comment]
> Unfortunately I don't have much time available for this project at the moment. I don't know when I will have time to look at this huge PR in detail.
> 
> Please note, unless https://github.com/martis42/depend_on_what_you_use/issues/11 is decided pro "clang based" I would not merge this PR.
Yeah, I pretty know that. I just want to see myself what need be done to support conditional includes via the clang-based  approach and present you a feel what it would be like. This PR serves for communication purpose. Many points in this Draft PR should be done even if we use other approches to parse includes.

> Regarding your concrete question. Typically one looks for an upstream source of pre-compiled binaries for clang and then downloads them via `http_archive` and uses select statements and the platforms concept to choose the correct binary for the current execution platform. Alternatively one introduces a toolchain and tells the user to provide clang in any way he/she sees befitting while configuring the toolchain.

So it may not be ok if I packaged/distributed clang-bindings-standalone to PYPI, and then depend on it via 
```
poetry add clang-bindings-standalone
```
, right?

**Comment by martis42** [comment]
@storypku 
Sorry for keeping you waiting so long.
For now I decided to not use `clang.cindex` and instead rely on `pcpp`. See [the closed issue #11](https://github.com/martis42/depend_on_what_you_use/issues/11#issuecomment-1528874099).

I am sorry you invested so much without it being merged. For now I feel more comfortable using `pcpp`. Please be aware your PR did help me a lot in coming up with the solution which is now part of DWYU :+1:

**Comment by storypku** [comment]
> I am sorry you invested so much without it being merged. For now I feel more comfortable using `pcpp`. Please be aware your PR did help me a lot in coming up with the solution which is now part of DWYU +1

Hi @martis42 ,
   It is OK for me to have this PR not merged. After careful rethought, I agree with your opinions on that Clang bindings was too heavy and not portable enough for DWYU, not to mention some inabilities It seems to processing corner cases (e.g. defines from transitively included header files) in my PR.

Regards,
Jiaming Liu

**Pull request closed without merging**
