### PR TITLE
Add more C headers

### PR DESCRIPTION
**Pull request by steple**
I stumbled upon these.

### CODE REVIEW

**Comment by martis42** [comment]
@steple 
Thanks for proposing this. I won't accept this PR. Not because I reject the proposal itself, but because I want to consistently add all C library and POSIX C library headers. The current list was based on https://en.cppreference.com/w/cpp/header which however ignores many common C headers.

**Comment by martis42** [comment]
P.S.: If you need a fast solution you can provide yourself include statements which shall be ignored, see this example: https://github.com/martis42/depend_on_what_you_use/tree/main/examples/ignoring_includes

**Comment by steple** [comment]
`extra_ignore_include_paths` works perfectly for my use case, thank you.

**Comment by martis42** [comment]
@steple 
https://github.com/martis42/depend_on_what_you_use/pull/248 should help with your issue in the long term.

**Pull request closed without merging**
